
-- =====================
-- ENUMS
-- =====================
CREATE TYPE public.user_role AS ENUM ('client', 'technician', 'admin');
CREATE TYPE public.machine_type AS ENUM ('color', 'noir_blanc');
CREATE TYPE public.contract_status AS ENUM ('actif', 'suspendu', 'terminé');
CREATE TYPE public.incident_category AS ENUM ('panne', 'maintenance', 'consommable', 'autre');
CREATE TYPE public.incident_priority AS ENUM ('basse', 'normale', 'haute', 'urgente');
CREATE TYPE public.incident_status AS ENUM ('nouveau', 'assigné', 'en_cours', 'résolu', 'fermé');
CREATE TYPE public.alert_type AS ENUM ('panne', 'toner_bas', 'autre');

-- =====================
-- PROFILES
-- =====================
CREATE TABLE public.profiles (
    id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role        public.user_role NOT NULL DEFAULT 'client',
    full_name   TEXT,
    phone       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================
-- CLIENTS
-- =====================
CREATE TABLE public.clients (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_client  TEXT NOT NULL UNIQUE,
    ninea       TEXT UNIQUE,
    email       TEXT,
    telephone   TEXT,
    adresse     TEXT,
    ville       TEXT,
    active      BOOLEAN NOT NULL DEFAULT true
);

-- =====================
-- MACHINES
-- =====================
CREATE TABLE public.machines (
    numero_serie    TEXT PRIMARY KEY,
    marque          TEXT NOT NULL,
    modele          TEXT NOT NULL,
    type            public.machine_type,
    localisation    TEXT,
    active          BOOLEAN NOT NULL DEFAULT true
);

-- =====================
-- CONTRACTS
-- =====================
CREATE TABLE public.contracts (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    numero_contrat      TEXT NOT NULL UNIQUE,
    client_id           BIGINT NOT NULL REFERENCES public.clients(id),
    machine_id          TEXT NOT NULL REFERENCES public.machines(numero_serie),
    date_debut          DATE NOT NULL,
    date_renouvellement DATE,
    lieu_installation   TEXT,
    statut              public.contract_status NOT NULL DEFAULT 'actif',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================
-- CLIENT_PROFILES
-- Vincula usuario del portal con empresa cliente
-- =====================
CREATE TABLE public.client_profiles (
    profile_id  UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    client_id   BIGINT NOT NULL REFERENCES public.clients(id),
    verified_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (profile_id, client_id)
);

-- =====================
-- INCIDENTS
-- =====================
CREATE TABLE public.incidents (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id          UUID NOT NULL REFERENCES public.contracts(id),
    machine_id           TEXT NOT NULL REFERENCES public.machines(numero_serie),
    opened_by            UUID REFERENCES public.profiles(id),
    assigned_to          UUID REFERENCES public.profiles(id),
    title                TEXT NOT NULL,
    description          TEXT,
    category             public.incident_category NOT NULL DEFAULT 'panne',
    priority             public.incident_priority NOT NULL DEFAULT 'normale',
    status               public.incident_status NOT NULL DEFAULT 'nouveau',
    rapport_intervention TEXT,
    autres_pieces        TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at          TIMESTAMPTZ,
    closed_at            TIMESTAMPTZ
);

-- =====================
-- PARTS (lista fija)
-- =====================
CREATE TABLE public.parts (
    id      SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    TEXT NOT NULL UNIQUE
);

INSERT INTO public.parts (name) VALUES
    ('Four'),
    ('Transfer Belt'),
    ('Tambour BK'),
    ('Tambour C'),
    ('Tambour M'),
    ('Tambour Y'),
    ('Toner BK'),
    ('Toner C'),
    ('Toner M'),
    ('Toner Y'),
    ('Cassette'),
    ('Rouleau Pression');

-- =====================
-- INCIDENT_PARTS
-- =====================
CREATE TABLE public.incident_parts (
    incident_id UUID NOT NULL REFERENCES public.incidents(id) ON DELETE CASCADE,
    part_id     SMALLINT NOT NULL REFERENCES public.parts(id),
    PRIMARY KEY (incident_id, part_id)
);

-- =====================
-- INCIDENT_PHOTOS
-- =====================
CREATE TABLE public.incident_photos (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    incident_id  UUID NOT NULL REFERENCES public.incidents(id) ON DELETE CASCADE,
    uploaded_by  UUID REFERENCES public.profiles(id),
    storage_path TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================
-- INCIDENT_HISTORY (audit trail)
-- =====================
CREATE TABLE public.incident_history (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    incident_id UUID NOT NULL REFERENCES public.incidents(id) ON DELETE CASCADE,
    changed_by  UUID REFERENCES public.profiles(id),
    old_status  TEXT,
    new_status  TEXT,
    comment     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================
-- CSAT_RESPONSES
-- =====================
CREATE TABLE public.csat_responses (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    incident_id  UUID NOT NULL REFERENCES public.incidents(id),
    token        TEXT NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
    rating       SMALLINT CHECK (rating >= 1 AND rating <= 5),
    comment      TEXT,
    responded_at TIMESTAMPTZ
);

-- =====================
-- PRINCITY_ALERTS
-- =====================
CREATE TABLE public.princity_alerts (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    received_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    client_raw       TEXT,
    client_id        BIGINT REFERENCES public.clients(id),
    machine_id       TEXT REFERENCES public.machines(numero_serie),
    site             TEXT,
    severity         TEXT,
    competence_level TEXT,
    ip_address       TEXT,
    mac_address      TEXT,
    modele           TEXT,
    description      TEXT,
    alert_type       public.alert_type DEFAULT 'autre',
    incident_id      UUID REFERENCES public.incidents(id),
    processed        BOOLEAN NOT NULL DEFAULT false,
    processed_at     TIMESTAMPTZ
);

-- =====================
-- TRIGGER: updated_at automático en incidents
-- =====================
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER incidents_updated_at
    BEFORE UPDATE ON public.incidents
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- =====================
-- TRIGGER: crear profile automáticamente al registrar usuario
-- =====================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name)
    VALUES (NEW.id, NEW.raw_user_meta_data->>'full_name');
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =====================
-- RLS — activado en todas las tablas
-- Las políticas se añadirán al construir el frontend
-- service_role bypassa RLS (para Edge Functions y agente)
-- =====================
ALTER TABLE public.profiles         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.machines         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contracts        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_profiles  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parts            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incident_parts   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incident_photos  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incident_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.csat_responses   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.princity_alerts  ENABLE ROW LEVEL SECURITY;
