-- =====================================================================
-- Fase 0 — Historial de piezas: homogeneizar el modelo + ampliar catálogo
-- Spec: docs/superpowers/specs/2026-06-15-historial-piezas-anomalias-design.md
-- =====================================================================

-- 1) Cantidad en piezas de incidencia (averías).
--    `maintenance_parts` ya tiene `quantity`; igualamos `incident_parts`
--    para que ambos orígenes sean homogéneos de cara al historial y al
--    futuro agente de anomalías. DEFAULT 1 deja coherentes los registros
--    históricos (1 unidad por pieza marcada).
ALTER TABLE public.incident_parts
  ADD COLUMN IF NOT EXISTS quantity int NOT NULL DEFAULT 1
    CHECK (quantity > 0);

-- 2) Dos piezas nuevas en el catálogo fijo.
--    Se insertan con id explícito (la PK es GENERATED BY DEFAULT, lo permite)
--    para que coincidan con src/lib/parts.ts. ON CONFLICT → idempotente.
INSERT INTO public.parts (id, name) VALUES
  (13, 'ADF'),
  (14, 'Poubelle Transfer')
ON CONFLICT (id) DO NOTHING;

-- 3) Resincronizar la secuencia identity tras el insert con id explícito,
--    para que los próximos inserts automáticos no choquen con 13/14.
SELECT setval(
  pg_get_serial_sequence('public.parts', 'id'),
  (SELECT MAX(id) FROM public.parts)
);
